// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.2
// source: internal/grpc/proto/consensus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []byte                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_internal_grpc_proto_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardRequest) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ForwardRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,4,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_internal_grpc_proto_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ForwardResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ForwardResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

var File_internal_grpc_proto_consensus_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_consensus_proto_rawDesc = "" +
	"\n" +
	"#internal/grpc/proto/consensus.proto\x12\tconsensus\"I\n" +
	"\x0eForwardRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\fR\acommand\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\"z\n" +
	"\x0fForwardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vleader_addr\x18\x04 \x01(\tR\n" +
	"leaderAddr2T\n" +
	"\tConsensus\x12G\n" +
	"\x0eForwardCommand\x12\x19.consensus.ForwardRequest\x1a\x1a.consensus.ForwardResponseB9Z7github.com/eleven-am/auto-consensus/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_consensus_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_consensus_proto_rawDescData []byte
)

func file_internal_grpc_proto_consensus_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_consensus_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_consensus_proto_rawDesc), len(file_internal_grpc_proto_consensus_proto_rawDesc)))
	})
	return file_internal_grpc_proto_consensus_proto_rawDescData
}

var file_internal_grpc_proto_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_proto_consensus_proto_goTypes = []any{
	(*ForwardRequest)(nil),  // 0: consensus.ForwardRequest
	(*ForwardResponse)(nil), // 1: consensus.ForwardResponse
}
var file_internal_grpc_proto_consensus_proto_depIdxs = []int32{
	0, // 0: consensus.Consensus.ForwardCommand:input_type -> consensus.ForwardRequest
	1, // 1: consensus.Consensus.ForwardCommand:output_type -> consensus.ForwardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_consensus_proto_init() }
func file_internal_grpc_proto_consensus_proto_init() {
	if File_internal_grpc_proto_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_consensus_proto_rawDesc), len(file_internal_grpc_proto_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_consensus_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_consensus_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_consensus_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_consensus_proto = out.File
	file_internal_grpc_proto_consensus_proto_goTypes = nil
	file_internal_grpc_proto_consensus_proto_depIdxs = nil
}
